import Phaser from 'phaser';
import { PLAYER, WEAPONS } from '../config.js';
import { SFX } from '../systems/FX.js';
import { Grenade } from './Grenade.js';

export class Player extends Phaser.Physics.Arcade.Sprite {
  constructor(scene, x, y) {
    super(scene, x, y, 'player', 0);
    scene.add.existing(this);
    scene.physics.add.existing(this);
    this.setDepth(30);
    this.body.setCircle(PLAYER.radius, this.width / 2 - PLAYER.radius, this.height / 2 - PLAYER.radius);
    this.body.setCollideWorldBounds(true);

    // ── Core stats ─────────────────────────────────────────────────────────
    this.hp           = PLAYER.hp;
    this.hpMax        = PLAYER.hp;
    this.ammo         = PLAYER.ammoMax;
    this.ammoTimers   = [];
    this.fireCooldown = 0;
    this.lastHurtAt   = -99999;
    this.superCharge  = 0;
    this.alive        = true;
    this.hiddenInBush = false;
    this.isRegenerating = false;
    this._hurtStaggerMs = 0;
    this._wKickT        = 0;
    this.accuracyMult   = 1.0;
    this.hitStreak      = 0;
    this.runMaxCombo    = 1.0;

    // ── Per-run upgrade stat layer ──────────────────────────────────────────
    // Identity-valued multipliers applied at each stat's read site (never by
    // mutating the shared PLAYER config — that would leak across runs). Reset
    // for free every run since Player is only rebuilt on scene restart.
    this.dmgMult           = 1;
    this.reloadMult        = 1;
    this.moveMult          = 1;
    this.dashChargesBonus  = 0;
    this.dashRechargeMult  = 1;
    this.superGainMult     = 1;
    this.regenMult         = 1;
    this._upgrades         = [];

    // ── Aiming state ───────────────────────────────────────────────────────
    this.facing      = -Math.PI / 2;
    this.aim         = -Math.PI / 2;
    this.aiming      = false;
    this.superAim    = -Math.PI / 2;
    this.superAiming = false;

    // ── Secondary weapon slot ──────────────────────────────────────────────
    // null means pistol only. Set by equipSecondary(weaponId).
    this.secondary      = null;  // weapon id string
    this.secondaryAmmo  = 0;     // rifle ammo / detonator charges / flame fuel %

    // Burst fire state (rifle)
    this._burstRemaining = 0;
    this._burstTimer     = 0;
    this._burstAngle     = 0;

    // Flamethrower held-fire state
    this.flameActive  = false;   // read by GameScene for damage cone
    this.flameAngle   = 0;
    this._flameDrain  = 0;       // accumulator for fuel drain

    // ── Animation helpers ──────────────────────────────────────────────────
    this._fireAnimTimer = 0;
    this.recoilT        = 0;
    this.revealTimer    = 0; // timer to reveal player when firing in bush
    this.dashCharges    = (PLAYER.dashChargesMax || 3) + this.dashChargesBonus;
    this.dashRechargeTimer = 0;
    this.isDashing      = false;
    this.dashTimer      = 0;
    this.dashAngle      = 0;

    // ── Movement ramp ──────────────────────────────────────────────────────
    // Target velocity set by setMoveInput; preUpdate eases body.velocity
    // toward it instead of snapping. Kills the "dragging picture" feel.
    this._moveTargetX = 0;
    this._moveTargetY = 0;
    // Smoothed move-vs-still envelope (0..1) for anim crossfade + scale.
    this._moveEnv = 0;

    // ── Visual accessories ─────────────────────────────────────────────────
    this.shadow = scene.add.image(x, y + 12, 'shadow')
      .setDepth(this.depth - 1).setAlpha(0.35);

    // "You are here" glow ring — Mando-cyan, always visible so the player can
    // spot themselves at a glance on small screens.
    this.glowRing = scene.add.graphics().setDepth(this.depth - 2);
    this.glowRing.fillStyle(0x40c8ff, 0.18);
    this.glowRing.fillCircle(0, 0, PLAYER.radius + 14);
    this.glowRing.lineStyle(2, 0x80e8ff, 0.75);
    this.glowRing.strokeCircle(0, 0, PLAYER.radius + 8);
    this.glowRing.setPosition(x, y);
    this._glowPulse = 0;

    // Super-ready aura: extra wider red/orange ring that only shows when
    // the super meter is full. Pulses faster than the cyan you-are-here.
    this.superAura = scene.add.graphics().setDepth(this.depth - 3).setVisible(false);
    this._auraPulse = 0;

    // Damage shield generated by hacking slicing ports
    this.shieldRing = scene.add.graphics().setDepth(this.depth + 3).setVisible(false);
    this.shieldHp = 0;

    this.play('mando-idle-front');
    // Baseline scale (1.0)
    this.setScale(1.0);

    // ── Weapon overlay: held by the character, rotates to match aim. ─────
    // The body itself never rotates — the weapon does. This is how
    // shipping 2D top-down games (Brawl Stars etc.) handle aim direction.
    this.weaponSprite = scene.add.image(x, y, 'wpn-pistol')
      .setDepth(this.depth + 1)
      .setOrigin(0.15, 0.5)  // pivot near the grip so the barrel swings forward
      .setScale(1.0);
  }

  // ── Movement / aiming inputs (called by HUD joysticks) ────────────────────

  setMoveInput(vec) {
    if (!this.alive) { this._moveTargetX = 0; this._moveTargetY = 0; return; }
    // Hurt-stagger: ignore joystick input briefly so the knockback shove
    // is actually visible before the player resumes control.
    if (this._hurtStaggerMs > 0) return;
    if (vec?.force > 0) {
      const speed = PLAYER.speed * this.moveMult;
      this._moveTargetX = vec.x * speed * vec.force;
      this._moveTargetY = vec.y * speed * vec.force;
      this.facing = Math.atan2(vec.y, vec.x);
      // Body NEVER rotates — only the weapon overlay does (handled in preUpdate).
      // When not aiming, the weapon follows the movement direction.
    } else {
      this._moveTargetX = 0;
      this._moveTargetY = 0;
    }
  }

  setAimInput(vec) {
    if (!this.alive) return;
    if (vec?.force > 0) {
      this.aiming = true;
      this.aim    = Math.atan2(vec.y, vec.x);
      // Flamethrower: fire while held
      if (this.secondary === 'flamethrower' && this.secondaryAmmo > 0) {
        this.flameActive = true;
        this.flameAngle  = this.aim;
      }
    } else {
      this.aiming      = false;
      this.flameActive = false;
    }
  }

  releaseAim(vec) {
    if (!this.alive) return;
    this.flameActive = false; // always stop flame on release
    if (this.secondary === 'flamethrower') {
      this.aiming = false;
      return;
    }

    let dir;
    if (vec && vec.force > 0.05) {
      dir = Math.atan2(vec.y, vec.x);
    } else {
      // Auto-aim at closest enemy
      const target = this.scene.findNearestEnemy(this.x, this.y);
      if (target) {
        dir = Math.atan2(target.y - this.y, target.x - this.x);
        this.facing = dir;
        this.aim = dir;
      } else {
        dir = this.aim;
      }
    }

    this.tryFire(dir);
    this.aiming = false;
  }

  setSuperAimInput(vec) {
    if (!this.alive) return;
    if (vec?.force > 0) {
      this.superAiming = true;
      this.superAim    = Math.atan2(vec.y, vec.x);
    } else {
      // Auto mode: preview the nearest enemy so the cone points where the shot
      // will actually go (kept in sync each frame while held — see preUpdate).
      this.superAiming = true;
      this.superAim    = this._autoAimAngle();
    }
  }

  releaseSuperAim(vec) {
    if (!this.alive) return;
    let angle;
    if (vec && vec.force > 0.05) {
      angle = Math.atan2(vec.y, vec.x);
    } else {
      // Auto-aim super at closest enemy
      const target = this.scene.findNearestEnemy(this.x, this.y);
      if (target) {
        angle = Math.atan2(target.y - this.y, target.x - this.x);
        this.facing = angle;
        this.superAim = angle;
      } else {
        angle = this.facing;
      }
    }
    this.superAiming = false;
    this.tryFireSuper(angle);
  }

  // Keyboard super (Space): tap = auto-aim fire, hold = manual aim that
  // tracks facing (see preUpdate), fires on release.
  beginKeyboardSuperAim() {
    this._kbSuperHold = true;
    this.setSuperAimInput(null);
  }

  endKeyboardSuperAim() {
    this._kbSuperHold = false;
    // Keyboard super always auto-aims the nearest enemy — matches the previewed
    // cone. Manual precision aiming stays on the touch super stick.
    this.releaseSuperAim(null);
  }

  // ── Firing ────────────────────────────────────────────────────────────────

  // Angle to the nearest enemy (what an auto-aim shot will use), or the current
  // facing if the room is empty. Used to make the aim cone preview the actual
  // auto-target instead of the move direction.
  _autoAimAngle() {
    const t = this.scene.findNearestEnemy?.(this.x, this.y);
    return t ? Math.atan2(t.y - this.y, t.x - this.x) : this.facing;
  }

  keyboardFire() {
    if (!this.alive) return;
    this.tryFire(this._autoAimAngle());
  }

  tryFire(angleOverride) {
    if (!this.alive) return false;
    const dir = typeof angleOverride === 'number' ? angleOverride
      : this.aiming ? this.aim : this.facing;

    // Unify visual + shot direction: whatever we fire along, the body/weapon
    // face it too. Without this, an auto-aim shot flies at the target while the
    // gun still points along the move stick — bolts appear to leave the player's
    // back and the character never turns to the enemy.
    this.facing = dir;
    this.aim    = dir;

    this.revealTimer = 1500; // Reveal player when shooting

    // Route through active secondary weapon
    if (this.secondary === 'rifle' && this.secondaryAmmo > 0) {
      return this._startBurst(dir);
    }
    if (this.secondary === 'detonator' && this.secondaryAmmo > 0) {
      return this._throwDetonator(dir);
    }
    // Default: pistol
    return this._firePistol(dir);
  }

  _firePistol(dir) {
    if (this.fireCooldown > 0) return false;
    if (this.ammo <= 0) return false;
    this.fireCooldown  = PLAYER.fireCooldownMs;
    this.ammo         -= 1;
    this.ammoTimers.push(PLAYER.ammoReloadMs * this.reloadMult);
    this.recoilT       = 110;
    this._wKickT       = 80;
    this._fireAnimTimer = 140;
    this.scene.events.emit('player-fire', dir);
    SFX.shoot();
    return true;
  }

  _startBurst(dir) {
    if (this.fireCooldown > 0) return false;
    const cfg = WEAPONS.rifle;
    this.fireCooldown    = cfg.fireCooldownMs;
    this._burstRemaining = cfg.burstCount;
    this._burstTimer     = 0;
    this._burstAngle     = dir;
    this.recoilT         = 80;
    this._wKickT         = 60;
    this._fireAnimTimer  = 160;
    SFX.shoot();
    return true;
  }

  _fireBurstShot() {
    const cfg = WEAPONS.rifle;
    this.secondaryAmmo -= 1;
    this.scene.events.emit('player-fire-rifle', this._burstAngle);
    SFX.shoot();
    if (this.secondaryAmmo <= 0) {
      this._burstRemaining = 0;
      this._equipNothing();
    }
  }

  _throwDetonator(dir) {
    if (this.fireCooldown > 0) return false;
    const cfg            = WEAPONS.detonator;
    this.secondaryAmmo  -= 1;
    this.fireCooldown    = 400;
    this._fireAnimTimer  = 200;
    this.recoilT         = 80;
    const spd = cfg.throwSpeed;
    const bx  = this.x + Math.cos(dir) * (PLAYER.radius + 10);
    const by  = this.y + Math.sin(dir) * (PLAYER.radius + 10);
    const grn = new Grenade(this.scene, bx, by, Math.cos(dir) * spd, Math.sin(dir) * spd);
    this.scene.grenades?.add(grn);
    SFX.shootSuper();
    this.scene.events.emit('secondary-ammo-changed');
    if (this.secondaryAmmo <= 0) this._equipNothing();
    return true;
  }

  // Flamethrower: drains each frame via GameScene; we just expose flameActive
  consumeFlame(delta) {
    const cfg = WEAPONS.flamethrower;
    this.revealTimer = 1000; // Keep player revealed during flamethrower
    this._flameDrain += cfg.drainPerSec * delta / 1000;
    if (this._flameDrain >= 1) {
      const drain        = Math.floor(this._flameDrain);
      this._flameDrain  -= drain;
      this.secondaryAmmo = Math.max(0, this.secondaryAmmo - drain);
      this.scene.events.emit('secondary-ammo-changed');
    }
    if (this.secondaryAmmo <= 0) {
      this.flameActive = false;
      this._equipNothing();
    }
  }

  // ── Super ─────────────────────────────────────────────────────────────────

  tryFireSuper(angleOverride) {
    if (!this.alive) return false;
    if (this.superCharge < PLAYER.superHitsToCharge) return false;
    this.superCharge = 0;
    this.revealTimer = 1500; // Reveal player
    const dir = typeof angleOverride === 'number' ? angleOverride
      : this.superAiming ? this.superAim : this.aiming ? this.aim : this.facing;
    // Face the super the same way — see tryFire.
    this.facing   = dir;
    this.superAim = dir;
    this.aim      = dir;
    this.recoilT        = 260;
    this._wKickT        = 180;   // bigger kick for the super
    this._fireAnimTimer = 240;
    this.scene.events.emit('player-fire-super', dir);
    SFX.shootSuper();
    return true;
  }

  tryDash() {
    if (!this.alive) return;
    if (isNaN(this.dashCharges) || !isFinite(this.dashCharges)) {
      this.dashCharges = (PLAYER.dashChargesMax || 3) + this.dashChargesBonus;
    }
    if (this.dashCharges <= 0) return;
    if (this.isDashing) return;
    if (this._hurtStaggerMs > 0) return;

    this.dashCharges--;
    this.isDashing = true;

    // Detect adjacent cover for Vault Dash
    let targetSpot = null;
    let minAngleDiff = Infinity;
    let desiredAngle = this.facing;
    if (this._moveTargetX !== 0 || this._moveTargetY !== 0) {
      desiredAngle = Math.atan2(this._moveTargetY, this._moveTargetX);
    }

    if (this.scene.coverRegistry && this.scene.coverRegistry.spots) {
      for (const spot of this.scene.coverRegistry.spots) {
        const dx = spot.x - this.x;
        const dy = spot.y - this.y;
        const dist = Math.hypot(dx, dy);

        // Only lock onto covers within 300px and not already hugging them (dist > 45px)
        if (dist > 45 && dist <= 300) {
          const angleToSpot = Math.atan2(dy, dx);
          const diff = Math.abs(Phaser.Math.Angle.ShortestBetween(desiredAngle * 180 / Math.PI, angleToSpot * 180 / Math.PI));
          if (diff <= 35 && diff < minAngleDiff) {
            minAngleDiff = diff;
            targetSpot = spot;
          }
        }
      }
    }

    if (targetSpot) {
      const dx = targetSpot.x - this.x;
      const dy = targetSpot.y - this.y;
      const dist = Math.hypot(dx, dy);
      
      this.dashAngle = Math.atan2(dy, dx);
      // Adaptive slide duration timer: scale time to match travel distance to cover edge
      const dashSpeed = PLAYER.dashSpeed || 950;
      const travelDist = Math.max(40, dist - 35); // offset cover radius
      this.dashTimer = Math.max(100, Math.min(400, (travelDist / dashSpeed) * 1000));
    } else {
      this.dashAngle = desiredAngle;
      this.dashTimer = PLAYER.dashDurationMs || 240;
    }

    if (isNaN(this.dashAngle) || !isFinite(this.dashAngle)) {
      this.dashAngle = 0;
    }

    this.scene.fx?.dustPuff?.(this.x, this.y + 14);
    SFX.dash();
    this.scene.events.emit('player-dash', this.dashCharges);
    this.scene.events.emit('player-dash-sound', this.x, this.y);
  }

  // ── Secondary weapon management ───────────────────────────────────────────

  equipSecondary(weaponId) {
    const cfg       = WEAPONS[weaponId];
    if (!cfg) return;
    this.secondary  = weaponId;
    // Set initial ammo/fuel/charges
    if (weaponId === 'rifle')        this.secondaryAmmo = cfg.totalAmmo;
    else if (weaponId === 'flamethrower') this.secondaryAmmo = cfg.fuel;
    else if (weaponId === 'detonator')    this.secondaryAmmo = cfg.charges;
    this.scene.events.emit('secondary-equipped', weaponId);
    this.scene.events.emit('secondary-ammo-changed');
    SFX.waveStart(); // pickup chime
  }

  _equipNothing() {
    this.secondary     = null;
    this.secondaryAmmo = 0;
    this.flameActive   = false;
    this.scene.events.emit('secondary-equipped', null);
    this.scene.events.emit('secondary-ammo-changed');
  }

  // ── Damage / death ────────────────────────────────────────────────────────

  addShield(amount) {
    this.shieldHp = Math.min(PLAYER.shieldHpMax, this.shieldHp + amount);
    this.shieldRing.setVisible(true);
  }

  damage(amount, hitDirRad = null) {
    if (!this.alive) return;
    if (this.isDashing) return; // i-frames (invincibility during dash)
    
    // Shield absorption logic
    if (this.shieldHp > 0) {
      const absorbed = Math.min(amount, this.shieldHp);
      this.shieldHp -= absorbed;
      amount -= absorbed;
      this.scene.fx.impactRing?.(this.x, this.y, 0x00ffff);
      if (this.shieldHp <= 0) {
        SFX.hit?.();
      }
    }
    
    if (amount <= 0) return;

    this.hp         = Math.max(0, this.hp - amount);
    this.scene.runDamageTaken = (this.scene.runDamageTaken || 0) + amount;
    this.lastHurtAt = this.scene.time.now;
    // Knockback shove if we know which direction we got hit from. Mirrors the
    // enemy stagger system: brief input-suspension window so the slide reads.
    if (typeof hitDirRad === 'number') {
      const kbStr = 220;
      this.body.velocity.x += Math.cos(hitDirRad) * kbStr;
      this.body.velocity.y += Math.sin(hitDirRad) * kbStr;
      this._hurtStaggerMs = 110;
    }
    this.scene.events.emit('player-hurt', amount, hitDirRad);
    SFX.hurt();
    if (this.hp <= 0) this.die();
  }

  onHitLanded() {
    this.hitStreak++;
    if (this.hitStreak >= 6) {
      this.accuracyMult = 2.0;
    } else if (this.hitStreak >= 4) {
      this.accuracyMult = 1.5;
    } else if (this.hitStreak >= 2) {
      this.accuracyMult = 1.2;
    } else {
      this.accuracyMult = 1.0;
    }
    this.runMaxCombo = Math.max(this.runMaxCombo || 1.0, this.accuracyMult);
    this.scene.events.emit('player-mult-changed', this.accuracyMult, this.hitStreak);
  }

  onShotMissed() {
    if (this.hitStreak > 0) {
      this.hitStreak = 0;
      this.accuracyMult = 1.0;
      this.scene.events.emit('player-mult-changed', this.accuracyMult, this.hitStreak);
    }
  }

  addSuperHit() {
    const max        = PLAYER.superHitsToCharge;
    const before     = this.superCharge;
    // Charge gains scaled by current combo multiplier
    this.superCharge = Math.min(max, this.superCharge + this.accuracyMult * this.superGainMult);
    if (before < max && this.superCharge >= max) {
      SFX.superReady();
      this.scene.events.emit('player-super-ready');
    } else {
      // Rising tick so each connecting pellet audibly feeds the meter.
      SFX.superTick(this.superCharge / max);
      // Halfway milestone chime on the crossing.
      if (before / max < 0.5 && this.superCharge / max >= 0.5) SFX.superHalf();
      this.scene.events.emit('player-super-changed');
    }
  }

  die() {
    this.alive       = false;
    this.flameActive = false;
    this.setVelocity(0, 0);
    this.jetEmitter?.stop();
    this.scene.events.emit('player-dead');
  }

  // ── Per-frame update ──────────────────────────────────────────────────────

  preUpdate(time, delta) {
    super.preUpdate?.(time, delta);

    // Keyboard super hold: the aim cone tracks the nearest enemy (the auto-aim
    // target) so it previews exactly where the shot will go on release.
    if (this._kbSuperHold && this.superAiming) {
      this.superAim = this._autoAimAngle();
    }

    // Recharge dash charges
    const dashMax = (PLAYER.dashChargesMax || 3) + this.dashChargesBonus;
    if (isNaN(this.dashCharges) || !isFinite(this.dashCharges)) {
      this.dashCharges = dashMax;
    }
    if (this.dashCharges < dashMax) {
      this.dashRechargeTimer += delta;
      if (this.dashRechargeTimer >= (PLAYER.dashRechargeMs || 2800) * this.dashRechargeMult) {
        this.dashCharges++;
        this.dashRechargeTimer = 0;
        this.scene.events.emit('player-dash-recharged', this.dashCharges);
      }
    } else {
      this.dashRechargeTimer = 0;
    }

    if (this.isDashing) {
      if (isNaN(this.dashTimer) || !isFinite(this.dashTimer)) {
        this.dashTimer = 0;
      }
      this.dashTimer -= delta;
      if (this.dashTimer <= 0) {
        this.isDashing = false;
        this.body.setVelocity(0, 0);
      } else {
        if (this.body) {
          const vx = Math.cos(this.dashAngle) * (PLAYER.dashSpeed || 950);
          const vy = Math.sin(this.dashAngle) * (PLAYER.dashSpeed || 950);
          if (!isNaN(vx) && !isNaN(vy) && isFinite(vx) && isFinite(vy)) {
            this.body.setVelocity(vx, vy);
          } else {
            this.body.setVelocity(0, 0);
          }
        }
        if (Math.random() < 0.45) {
          this.scene.fx?.dustPuff?.(this.x, this.y + 14);
        }
      }
    } else if (this._hurtStaggerMs > 0) {
      this._hurtStaggerMs -= delta;
      this.body.velocity.x *= 0.88;
      this.body.velocity.y *= 0.88;
    } else if (this.alive) {
      // Acceleration / deceleration ramp toward the target velocity set by
      // the joystick. Snapping instantly to top speed reads as "dragging a
      // picture"; ramping over ~3 frames reads as weight.
      const dt    = delta / 1000;
      const tx    = this._moveTargetX || 0;
      const ty    = this._moveTargetY || 0;
      const vx    = this.body.velocity.x;
      const vy    = this.body.velocity.y;
      const dx    = tx - vx;
      const dy    = ty - vy;
      const dMag  = Math.hypot(dx, dy);
      const rate  = (tx === 0 && ty === 0) ? PLAYER.decelPerSec : PLAYER.accelPerSec;
      const step  = rate * dt;
      if (dMag <= step) {
        this.body.setVelocity(tx, ty);
      } else {
        this.body.setVelocity(vx + (dx / dMag) * step, vy + (dy / dMag) * step);
      }
    }

    // Footstep dust puffs — drop a small particle puff every ~140ms while
    // the player is moving fast enough for it to read as running.
    const movingSq = this.body.velocity.x ** 2 + this.body.velocity.y ** 2;
    this._stepTimer = (this._stepTimer || 0) + delta;
    if (this.alive && movingSq > 8000 && this._stepTimer >= 140) {
      this._stepTimer = 0;
      this.scene.fx?.dustPuff?.(this.x, this.y + 14);
    }

    if (this.fireCooldown > 0) this.fireCooldown -= delta;

    // Burst fire tick (rifle)
    if (this._burstRemaining > 0) {
      this._burstTimer -= delta;
      if (this._burstTimer <= 0) {
        this._burstTimer = WEAPONS.rifle.burstDelayMs;
        this._fireBurstShot();
        this._burstRemaining -= 1;
      }
    }

    // Pistol ammo reload
    if (this.ammoTimers.length > 0) {
      this.ammoTimers[0] -= delta;
      if (this.ammoTimers[0] <= 0) {
        this.ammoTimers.shift();
        this.ammo = Math.min(PLAYER.ammoMax, this.ammo + 1);
        this.scene.events.emit('player-ammo-changed');
      }
    }

    // HP regen
    const isHealing = this.alive && this.hp < this.hpMax && time - this.lastHurtAt > PLAYER.regenDelayMs;
    this.isRegenerating = isHealing;
    if (isHealing) {
      this.hp = Math.min(this.hpMax, this.hp + (PLAYER.regenPerSec * this.regenMult * delta) / 1000);
      this.scene.events.emit('player-hp-changed');
      
      // Spawn healing sparkles bubbling upward (cyan)
      if (Math.random() < 0.25) {
        this.scene.fx?.healingSparkle?.(this.x + Phaser.Math.Between(-16, 16), this.y + Phaser.Math.Between(-12, 12));
      }
    }

    // ── Weapon overlay: hovers next to the character, rotated to aim ─────
    // The aim angle drives weapon rotation. When not aiming, the weapon
    // follows the move-facing so the character looks "ready" in the direction
    // they're walking. The overlay sits a small radius out from the character
    // center so it visually reads as "held in front" of them.
    if (this.weaponSprite) {
      const ang = this.superAiming ? this.superAim
                : this.aiming      ? this.aim
                : this.facing;
      // Pick the right weapon sprite for the equipped secondary.
      const wantTex = this.secondary === 'rifle' ? 'wpn-rifle'
                    : this.secondary === 'flamethrower' ? 'wpn-rifle'
                    : 'wpn-pistol';
      if (this.weaponSprite.texture.key !== wantTex) this.weaponSprite.setTexture(wantTex);
      // Recoil kick — when firing, the weapon visually slides BACKWARDS
      // from the player for ~80ms then springs back. Pure visual, doesn't
      // affect bullet spawn positions.
      if (this._wKickT > 0) this._wKickT -= delta;
      const kickBack = this._wKickT > 0 ? (this._wKickT / 80) * 7 : 0;
      const offset = PLAYER.radius - 4 - kickBack;
      this.weaponSprite.x = this.x + Math.cos(ang) * offset;
      this.weaponSprite.y = this.y + Math.sin(ang) * offset;
      this.weaponSprite.rotation = ang;
      this.weaponSprite.setFlipY(Math.abs(ang) > Math.PI / 2);
      this.weaponSprite.setAlpha(this.alive ? (this.hiddenInBush ? PLAYER.bushAlpha : 1) : 0);
    }

    // ── Y-sort: depth tracks world Y so entities occlude each other based
    // on their position rather than a fixed integer per type. Related
    // sprites (shadow, weapon, rings) ride small offsets around the body.
    this.setDepth(this.y);
    
    // Depth sort weapon based on facing direction (behind if facing North/back)
    const deg = Phaser.Math.RadToDeg(this.superAiming ? this.superAim : this.aiming ? this.aim : this.facing);
    const isFacingNorth = (deg < -45 && deg > -135);
    if (this.weaponSprite) {
      this.weaponSprite.setDepth(isFacingNorth ? this.y - 1 : this.y + 1);
    }
    this.glowRing.setDepth(this.y - 2);
    this.superAura.setDepth(this.y - 3);

    // Shadow + you-are-here glow ring (pulses softly).
    // Reactive shadow: drifts in the velocity direction (sells motion) and
    // squashes briefly during hurt-stagger or weapon kick (sells weight).
    const sVx     = this.body.velocity.x;
    const sVy     = this.body.velocity.y;
    const sDriftX = Phaser.Math.Clamp(sVx * 0.012, -3, 3);
    const sDriftY = Phaser.Math.Clamp(sVy * 0.008, -2, 2);
    const kickLift = this._wKickT > 0 ? -1 : 0;
    const staggerSquash = this._hurtStaggerMs > 0 ? 0.85 : 1;
    this.shadow.setPosition(this.x + sDriftX, this.y + 18 + sDriftY + kickLift);
    this.shadow.setScale(staggerSquash, staggerSquash);
    this.shadow.setDepth(this.y - 1);
    this._glowPulse += delta * 0.005;
    const pulse = 0.85 + 0.15 * Math.sin(this._glowPulse);
    this.glowRing.setPosition(this.x, this.y).setScale(pulse);
    this.glowRing.setAlpha(this.hiddenInBush ? 0.25 : 1);

    // Update shield indicator ring
    if (this.shieldHp > 0) {
      this.shieldRing.setVisible(true);
      this.shieldRing.clear();
      this.shieldRing.setPosition(this.x, this.y);
      this.shieldRing.setDepth(this.y + 3);
      const shieldPulse = 1.0 + 0.08 * Math.sin(time * 0.008);
      this.shieldRing.fillStyle(0x00d0ff, 0.12);
      this.shieldRing.fillCircle(0, 0, PLAYER.radius + 16);
      this.shieldRing.lineStyle(3, 0x00ffff, 0.85);
      this.shieldRing.strokeCircle(0, 0, (PLAYER.radius + 16) * shieldPulse);
    } else {
      this.shieldRing.setVisible(false);
    }

    // Super aura — now draws whenever the meter has ANY charge, brightening
    // as it fills (t = 0..1) so the player feels the super building toward
    // ready. At full charge it pulses; below full it's a steady dim-to-bright
    // glow scaled by t.
    const t = Math.min(1, this.superCharge / PLAYER.superHitsToCharge);
    if (t > 0) {
      const aGfx = this.superAura;
      aGfx.clear();
      let fillA, lineA, innerA, ringR;
      if (t >= 1) {
        // Full: the original pulsing ready-aura.
        this._auraPulse += delta * 0.012;
        const ap = 0.55 + 0.45 * Math.sin(this._auraPulse);
        fillA  = 0.10 + 0.10 * ap;
        lineA  = 0.7 + 0.3 * ap;
        innerA = 0.5 + 0.4 * ap;
        ringR  = PLAYER.radius + 18;
      } else {
        // Charging: steady glow that grows in intensity + radius with t.
        fillA  = 0.05 + 0.08 * t;
        lineA  = 0.25 + 0.45 * t;
        innerA = 0.15 + 0.35 * t;
        ringR  = PLAYER.radius + 10 + 8 * t;
      }
      aGfx.fillStyle(0xff4020, fillA);
      aGfx.fillCircle(0, 0, PLAYER.radius + 24);
      aGfx.lineStyle(3, 0xff6040, lineA);
      aGfx.strokeCircle(0, 0, ringR);
      aGfx.lineStyle(1.5, 0xffe080, innerA);
      aGfx.strokeCircle(0, 0, PLAYER.radius + 12);
      aGfx.setPosition(this.x, this.y).setVisible(true);
      aGfx.setAlpha(this.hiddenInBush ? 0.3 : 1);
    } else if (this.superAura.visible) {
      this.superAura.setVisible(false);
    }

    // Bush alpha
    this.setAlpha(this.hiddenInBush ? PLAYER.bushAlpha : 1);

    // ── Sprite animation ─────────────────────────────────────────────────
    // Use a smoothed move envelope (0..1) so the walk↔idle transition isn't
    // a binary snap. We still swap the anim key when the envelope crosses
    // the threshold, but the Y-scale stretch is continuous so the body
    // visually settles into / out of the gait.
    const speedSq  = this.body.velocity.x ** 2 + this.body.velocity.y ** 2;
    const moveT    = Math.min(1, speedSq / (PLAYER.speed * PLAYER.speed * 0.25));
    // Exponential smoothing toward target — ~140ms blend window.
    const blendK   = 1 - Math.exp(-delta / 140);
    this._moveEnv += (moveT - this._moveEnv) * blendK;
    const isMoving = this._moveEnv > 0.35;

    // Determine 4-directional anim suffix and flipX
    let dirSuffix = 'front';
    let flipX = false;

    let angAnim = this.facing;
    if (this.superAiming) {
      angAnim = this.superAim;
    } else if (this.aiming) {
      angAnim = this.aim;
    } else if (isMoving && this.body && (Math.abs(this.body.velocity.x) > 10 || Math.abs(this.body.velocity.y) > 10)) {
      angAnim = Math.atan2(this.body.velocity.y, this.body.velocity.x);
      this.facing = angAnim; // update facing to walk direction
    }

    const degAnim = Phaser.Math.RadToDeg(angAnim);
    if (degAnim >= -45 && degAnim <= 45) {
      dirSuffix = 'side';
      flipX = false; // facing East
    } else if (degAnim > 45 && degAnim < 135) {
      dirSuffix = 'front';
      flipX = false; // facing South
    } else if (degAnim >= 135 || degAnim <= -135) {
      dirSuffix = 'side';
      flipX = true;  // facing West
    } else {
      dirSuffix = 'back';
      flipX = false; // facing North
    }

    this.setFlipX(flipX);

    const baseKey = 'mando';
    let animKey = `${baseKey}-idle-${dirSuffix}`;
    if (this._fireAnimTimer > 0) {
      this._fireAnimTimer -= delta;
      animKey = `${baseKey}-fire-${dirSuffix}`;
    } else if (isMoving) {
      animKey = `${baseKey}-walk-${dirSuffix}`;
    }

    if (this.anims.currentAnim?.key !== animKey) {
      this.play(animKey);
    }

    // ── Recoil punch + idle breathing + move-envelope stretch ──────────
    // Recoil wins when active. Otherwise the body Y-scale eases between
    // idle (with subtle breathing) and walk (slight forward lean from the
    // move envelope), so transitions read as weight shifts not snaps.
    // Decay reveal timer
    if (this.revealTimer > 0) this.revealTimer -= delta;

    // ── Recoil punch + waddle / lean / bob walking animations ──────────
    if (this.isDashing) {
      this.angle = Math.sin(time * 0.05) * 15; // fast dodge roll spin
      this.setScale(1.0);
    } else if (this.recoilT > 0) {
      this.recoilT -= delta;
      this.setScale(1.0 * (1 - Math.max(0, this.recoilT / 110) * 0.12));
      this.angle = 0;
    } else if (this.alive && this._hurtStaggerMs <= 0) {
      if (isMoving) {
        this.angle = 0;
        this.setScale(1.0);
      } else {
        // Idle breathing Y-scale only (very subtle)
        this.angle = 0;
        const breath = Math.sin(time * 0.003) * 0.015;
        this.setScale(1.0, 1.0 + breath);
      }
    } else {
      this.angle = 0;
      this.setScale(1.0);
    }

  }

  destroy(fromScene) {
    this.shadow?.destroy();
    this.glowRing?.destroy();
    this.superAura?.destroy();
    this.shieldRing?.destroy();
    this.weaponSprite?.destroy();
    super.destroy(fromScene);
  }
}
