// All gameplay tunables live here so we can iterate on feel quickly.

export const VIEW = {
  width: 720,
  height: 1280,
};

export const WORLD = {
  width: 1600,
  height: 1600,
  bg: 0x14161c,
  bgDark: 0x0c0c12,
  bgCol: 0x2e3038,
  wallColor: 0x1e2028,
};

export const PLAYER = {
  hp: 1000,
  speed: 380,
  // Movement weight curve — px/s² ramps applied to body velocity each frame
  // so input doesn't snap to top speed (kills the "dragging picture" feel).
  accelPerSec: 4200,
  decelPerSec: 5000,
  dashChargesMax: 2,
  dashRechargeMs: 4000,
  dashSpeed: 800,
  dashDurationMs: 180,
  radius: 22,
  ammoMax: 3,
  ammoReloadMs: 520, // buffed by 35% (was 800ms)
  fireCooldownMs: 120,
  // Primary: single red blaster bolt
  pelletCount: 1,
  pelletSpreadDeg: 0,
  pelletDamage: 120,
  pelletSpeed: 900,
  pelletRange: 400,
  pelletRadius: 6,
  // Super: wrist-rocket barrage
  superHitsToCharge: 4, // buffed (was 8)
  superPellets: 5,
  superSpreadDeg: 30,
  superDamage: 600,
  superSpeed: 700,
  superRange: 560,
  superRadius: 12,
  superKnockback: 500,
  // HP regen
  regenDelayMs: 4000,
  regenPerSec: 100,
  // Bush alpha
  bushAlpha: 0.5,
  // Combat shield generated by hacking terminals
  shieldHpMax: 400,
};

// Secondary weapons (picked up in rooms)
export const WEAPONS = {
  rifle: {
    id: 'rifle',
    name: 'DC-15 RIFLE',
    totalAmmo: 27,       // 9 bursts
    burstCount: 3,
    burstDelayMs: 75,    // ms between burst shots
    damage: 90,
    speed: 940,
    range: 500,
    fireCooldownMs: 300,
  },
  flamethrower: {
    id: 'flamethrower',
    name: 'FLAMETHROWER',
    fuel: 100,            // percentage
    drainPerSec: 22,      // ~4.5 s of continuous fire
    damagePerSec: 250,
    range: 190,
    halfAngleDeg: 28,
  },
  detonator: {
    id: 'detonator',
    name: 'THERMAL DET.',
    charges: 3,
    throwSpeed: 510,
    fuseMs: 1100,
    blastRadius: 130,
    damage: 500,
  },
};

export const ENEMY = {
  grunt: {
    hp: 320,
    speed: 230,
    radius: 22,
    desiredRange: 350,
    fireCooldownMs: 1200,
    bulletSpeed: 360,     // slowed (was 520) for dodging
    bulletDamage: 100,    // lowered (was 140) for swarms
    bulletRange: 480,
    color: 0xdcdce8,
    eyeColor: 0x20ee20,
  },
  shooter: {
    hp: 450,
    speed: 190,
    radius: 22,
    desiredRange: 380,
    fireCooldownMs: 800,
    bulletSpeed: 420,     // slowed (was 640) for dodging
    bulletDamage: 130,    // lowered (was 180) for swarms
    bulletRange: 560,
    color: 0x181820,
    eyeColor: 0x20d020,
  },
};

export const BOSS = {
  hp: 12000,
  radius: 56,
  speed: 165,
  contactDamage: 300,
  phase2: 0.66,
  phase3: 0.33,
  chargeWindupMs: 700,
  chargeSpeed: 950,
  chargeDurationMs: 900,
  fanPellets: 11,
  fanSpreadDeg: 70,
  fanBulletSpeed: 380,
  fanBulletDamage: 180,
  fanBulletRange: 720,
  spawnCount: 3,
  attackCooldownMs: 1600,
  color: 0x0a0a0e,
  eyeColor: 0xff2020,
};

// Bacta vial healing pickup
export const HEALTH_ORB = {
  dropChance: 0.18,
  healAmount: 120,
  radius: 14,
  color: 0x1898e8,
  lifeMs: 8000,
};

export const HUDCFG = {
  joystickRadius: 90,
  joystickKnobRadius: 42,
  joystickMargin: 36,
  joystickBottom: 36,
};

export const COLORS = {
  player:        0x6a7080,
  playerOutline: 0x0a0c14,
  bullet:        0xff2828,
  bulletSuper:   0xffffff,
  enemyBullet:   0x10ee10,
  hpBack:        0x0a0e18,
  hpFront:       0x1898e8,
  hpLow:         0xee1010,
  ammoOn:        0xff2828,
  ammoOff:       0x1a1c22,
  superGauge:    0xee1010,
  superReady:    0xff5040,
  textShadow:    0x000000,
};

// Survival Arena Mode settings.
//   time       s   — round length
//   spawnRate  ms  — drip-spawn interval at round start
//   rampTo     ms  — drip interval at round end (pressure ramps linearly)
//   maxAlive       — drip pauses at this many living enemies (surges may
//                    briefly exceed it by a few)
//   surgeEvery s   — a surge (burst of surgeCount spawns) fires on this cadence
//   shooterMix 0-1 — chance a spawn is a shooter; the rest are grunt rushers
export const ARENA = {
  hangar:    { time: 60, spawnRate: 2600, rampTo: 1400, maxAlive: 10, surgeEvery: 20, surgeCount: 4, shooterMix: 0.25 },
  corridor:  { time: 60, spawnRate: 2300, rampTo: 1200, maxAlive: 12, surgeEvery: 20, surgeCount: 5, shooterMix: 0.30 },
  detention: { time: 75, spawnRate: 2000, rampTo: 1000, maxAlive: 14, surgeEvery: 18, surgeCount: 6, shooterMix: 0.35 },
  vader:     { time: 60, spawnRate: 1800, rampTo: 1000, maxAlive: 14, surgeEvery: 15, surgeCount: 6, shooterMix: 0.40 },
};

// Ally settings (turrets and soldiers)
export const ALLY = {
  turret: {
    hp: 1000,
    radius: 20,
    range: 500,
    fireCooldownMs: 500,
    damage: 80,
    bulletSpeed: 850,
  },
  soldier: {
    hp: 500,
    speed: 250,
    radius: 22,
    desiredRange: 300,
    fireCooldownMs: 650,
    bulletSpeed: 700,
    bulletDamage: 75,
    bulletRange: 450,
  },
};

